//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IvanovVDPractic1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IvanovPractic1BDEntities : DbContext
    {
        public IvanovPractic1BDEntities()
            : base("name=IvanovPractic1BDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dish_Type> Dish_Type { get; set; }
        public virtual DbSet<Dishes> Dishes { get; set; }
        public virtual DbSet<UsersData> UsersData { get; set; }
    }
}
