//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IvanovVDPractic1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dishes
    {
        public int DishID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<bool> InStoplist { get; set; }
        public Nullable<int> DishTypeID { get; set; }
    
        public virtual Dish_Type Dish_Type { get; set; }
    }
}
